### ISSUE TITLE
Client.get no method .get

### ISSUE THREAD

**Issue by sexybiggetje** [bartve/disconnect#12]
I get an internal error in database.js saying client doesn't have a method get.

Given the following code:
```javascript
var Discogs = require('disconnect').Client;
var dis;

function setupDiscogs(apiKey) {
    dis = new Discogs('HowMuchIsTheFish/1.0', {userToken: apiKey});

    var db = new dis.database();
    db.search(
    "Mind the gap",
    {
        "type": "release",
        "artist": "scooter",
        "year": "2004"
    }, function(err, data) {
        if (err) {
            console.log(err);
        } else {
            console.log(data);
        }
    });
}
```

This produces the following result:
```
/Users/x/node_modules/disconnect/lib/database.js:113
		client.get({url: util.addParams('/database/search', obj), authLevel: 1}, cal
		       ^
TypeError: Object [object Object] has no method 'get'
    at Object.database.search (/Users/x/node_modules/disconnect/lib/database.js:113:10)
    at setupDiscogs (/Users/x/source/howmuchisthe.fish/app.js:282:8)
```

**Comment by bartve** [comment]
```javascript
var db = new dis.database();
```
should be
```javascript
var db = dis.database();
```
or just:
```javascript
var db = new Discogs('HowMuchIsTheFish/1.0', {userToken: apiKey}).database();
```
Let me know if this was causing the error. Not much time to test myself right now.

**Comment by sexybiggetje** [comment]
I feel somewhat stupid now hehe. Thanks, this works great.

**Comment by bartve** [comment]
No problem! Glad it works now.
