### ISSUE TITLE
Error integrating in Aurelia

### ISSUE THREAD

**Issue by djcaesar9114** [bartve/disconnect#37]
Hello,
I'm using aurelia.io, and I'd like to use your npm package in my app.
I install it normally, typing `npm install disconnect --save` in the folder of my app.
I also edit `aurelia.json` correctly to insert in the `vendor-bundle.js` section :
```
          {
            "name": "disconnect",
            "path": "../node_modules/disconnect",
            "main": "index"
          },
```

Then I buikd my app typing `au build`, but I get this error:

```
{ uid: 8,
  name: 'writeBundles',
  branch: false,
  error: 
   { Error: ENOENT: no such file or directory, open '/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js'
       at Object.fs.openSync (fs.js:558:18)
       at Object.fs.readFileSync (fs.js:468:33)
       at Object.exports.readFileSync (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/file-system.js:49:13)
       at fileRead (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
       at Object.context.fileRead (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
       at Object.context.load (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
       at Module.load (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:832:29)
       at Module.fetch (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:822:66)
       at Module.check (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:854:30)
       at Module.enable (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:1173:22)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js',
     moduleTree: [ 'disconnect/index' ],
     fileName: '/home/cesar/projets/aurelia/tracklist-manager/node_modules/disconnect/index.js' },
  duration: [ 4, 789092986 ],
  time: 1490043332523 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error: 
   { Error: ENOENT: no such file or directory, open '/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js'
       at Object.fs.openSync (fs.js:558:18)
       at Object.fs.readFileSync (fs.js:468:33)
       at Object.exports.readFileSync (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/file-system.js:49:13)
       at fileRead (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
       at Object.context.fileRead (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
       at Object.context.load (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
       at Module.load (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:832:29)
       at Module.fetch (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:822:66)
       at Module.check (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:854:30)
       at Module.enable (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:1173:22)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js',
     moduleTree: [ 'disconnect/index' ],
     fileName: '/home/cesar/projets/aurelia/tracklist-manager/node_modules/disconnect/index.js' },
  duration: [ 8, 704096699 ],
  time: 1490043332559 }
{ Error: ENOENT: no such file or directory, open '/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.exports.readFileSync (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/file-system.js:49:13)
    at fileRead (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
    at Object.context.fileRead (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
    at Object.context.load (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
    at Module.load (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:832:29)
    at Module.fetch (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:822:66)
    at Module.check (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:854:30)
    at Module.enable (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:1173:22)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js',
  moduleTree: [ 'disconnect/index' ],
  fileName: '/home/cesar/projets/aurelia/tracklist-manager/node_modules/disconnect/index.js' }
```

I don't know what's wrong...
If you can help me, it would be great :)

**Comment by bartve** [comment]
Perhaps a dumb question, but is `util.js` actually in `/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js` ? because that's where aurelia is looking for it. I have never used aurelia, so I can't help you with that part I'm afraid.

**Comment by djcaesar9114** [comment]
Hello and thanks for your quick answer.
Actually no, it's not in this folder. All the node modules are in /home/cesar/projets/aurelia/tracklist-manager/node_modules/
Aurelia fetches all the other node modules correctly, there is only this one that it's looking in the root folder...

**Comment by djcaesar9114** [comment]
Actually I've got more info from Aurelia team:
https://github.com/aurelia/cli/issues/555

Apparently, several kinds of packages exist: for browsers and others. Yours is not for browsers. For the moment I don't understand everything, my knowledge in node is not big enough...
Do you plan on making your package for browsers?

**Comment by bartve** [comment]
Heh, I don't know anything about JS modules in browsers, so that won't help. Using this library client-side isn't really what you want as you're exposing your authentication (DiscogsAuth or OAuth) data.

**Comment by djcaesar9114** [comment]
OK, thank you :)
